apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.16.0 (0c01309)
  labels:
    io.kompose.service: kibana
  name: kibana
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: kibana
    spec:
      containers:
      - env:
        - name: ELASTICSEARCH_URL
          value: http://elasticsearch:9200
        - name: SERVER_NAME
          value: kibana
        image: docker.elastic.co/kibana/kibana:6.4.2
        livenessProbe:
          exec:
            command:
            - curl -f http://localhost:5601 || exit 1
          failureThreshold: 5
          periodSeconds: 30
          timeoutSeconds: 10
        name: kibana
        ports:
        - containerPort: 5601
        resources: {}
      restartPolicy: Always
